services:
  x2s:
    image: ghcr.io/lemmaalliance/x2s-docker:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/etc/x2s/config.json:ro
      - x2s_data:/data
    environment:
      - X2S_DATA_DIR=/data

volumes:
  x2s_data:
